- name: Configure servers
  hosts: servers
  become: true

  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
          - python3-venv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: true

    - name: De-armor Docker GPG key for APT
      command: gpg --dearmor --yes --output /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/debian
        suites: "{{ ansible_facts['distribution_release'] }}"
        components: stable
        signed_by: /etc/apt/keyrings/docker.gpg

    - name: Update apt and install Docker Engine
      apt:
        pkg:
          - docker-ce=5:28.5.2-1~debian.13~trixie # DO NOT KEEP 
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker>=7.1.0
        extra_args: --break-system-packages

    - name: Set DOMAIN environment variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: ^DOMAIN=
        line: DOMAIN={{ base_domain }}
