- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Add Docker's official repository (with GPG key)
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true
