[servers]
; test ansible_host=192.168.1.26 ansible_user=cooper ansible_python_interpreter=/usr/bin/python3
production ansible_host=192.168.1.25 ansible_user=cooper ansible_python_interpreter=/usr/bin/python3