- name: Create Servarr directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ apps_path }}/servarr"
    - "{{ apps_path }}/servarr/qbittorrent"
    - "{{ apps_path }}/servarr/qbittorrent/config"
    - "{{ apps_path }}/servarr/prowlarr"
    - "{{ apps_path }}/servarr/prowlarr/config"
    - "{{ apps_path }}/servarr/sonarr"
    - "{{ apps_path }}/servarr/sonarr/config"
    - "{{ apps_path }}/servarr/radarr"
    - "{{ apps_path }}/servarr/radarr/config"
    - "{{ apps_path }}/servarr/readarr"
    - "{{ apps_path }}/servarr/readarr/config"
    - "{{ apps_path }}/servarr/autobrr"
    - "{{ apps_path }}/servarr/autobrr/config"
    - /mnt/storage/media
    - /mnt/storage/media/downloads
    - /mnt/storage/media/movies
    - /mnt/storage/media/tv
    - /mnt/storage/media/books
  become: false

- name: Copy Servarr docker-compose
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../templates/servarr/docker-compose.yml"
    dest: "{{ apps_path }}/servarr/docker-compose.yml"
    mode: "0644"

- name: Deploy Servarr stack
  community.docker.docker_compose_v2:
    project_src: "{{ apps_path }}/servarr"
    state: present
  environment:
    DOMAIN: "{{ base_domain }}"
